apiVersion: v1
kind: ConfigMap
metadata: 
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
      - job_name: 'invoice-parser'
        static_configs:
          - targets: ['invoice-parser:8000']
