apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    
    scrape_configs:
      - job_name: 'invoice-parser'
        static_configs:
          - targets: ['invoice-parser-service:8000']
      - job_name: 'invoice-parser-metrics'
        static_configs:
          - targets: ['invoice-parser-service:8001']
