apiVersion: apps/v1
kind: Deployment
metadata:
    name: prometheus_app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: prometheus_app
    template:
        metadata:
            labels:
                app: prometheus_app
        spec:
            containers:
            - name: prometheus
              image: prom/prometheus
              ports: 
              - containerPort: 9090
              volumeMounts:
              - name: prometheus-config
                mountPath: /etc/prometheus
                
            volumes:
            - name: prometheus-config
              configMap: 
                name: prometheus-config
            
---
apiVersion: v1 
kind: Service
metadata:
    name: prometheus-service
spec:
    type: ClusterIP
    selector:
        app: prometheus_app
    ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
            
        