apiVersion: apps/v1
kind: Deployment
metadata: 
    name: invoice-parser
spec :
    replicas: 1
    selector:
        matchLabels:
            app: invoice-parser
    strategy:
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: invoice-parser
        spec:
            containers:
            - name: invoice-parser
              image: edgar403/invoice_parser:v1
              ports:
              - containerPort: 8000
    
---
apiVersion: v1
kind: Service
metadata:
    name: invoice-parser-service
spec:
    type: NodePort
    selector:
        app: invoice-parser
    ports:
      - protocol: TCP
        port: 8000
        targetPort: 8000
